/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package andres_masis_poo;

import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import java.util.LinkedList;

/**
 *
 * @author Andrés
 */
public class Interface extends javax.swing.JFrame {

    Items objeto = null;
    String procedencia = null;

    static LinkedList<Items> todos_objetos = new LinkedList<>();

    
    DatosApi pre = new DatosApi(); 
    // ARMA

     Armas weapon0 = new Armas(pre.listPrecio[0], "Armas", "Draktharr", 0, pre.listReviews[0], 0, 0, pre.listReviews[0]/3, pre.listReviews[0]/5);
     Armas weapon1 = new Armas(pre.listPrecio[1], "Armas", "Filo", 0, pre.listReviews[1], 0, 0, pre.listReviews[1]/3, pre.listReviews[1]/5);
     Armas weapon2 = new Armas(pre.listPrecio[2], "Armas", "Youmuu", 0, pre.listReviews[2], 0, pre.listReviews[2]/2, pre.listReviews[2]/3, 0);
     Armas weapon3 = new Armas(pre.listPrecio[3], "Armas", "Statikk", 0, pre.listReviews[3], 0, 0, pre.listReviews[3]/3, pre.listReviews[3]/5);
     Armas weapon4 = new Armas(pre.listPrecio[4], "Armas", "Guinsoo", 0, pre.listReviews[4], 0, 0, pre.listReviews[4]/3, pre.listReviews[4]/5);
     Armas weapon5 = new Armas(pre.listPrecio[5], "Armas", "Espadón", 0, pre.listReviews[5], 0, 0, pre.listReviews[5]/3, 0);
     Armas weapon6 = new Armas(pre.listPrecio[6], "Armas", "Rabadon", 0, pre.listReviews[6], 0, 0, pre.listReviews[6]/3, pre.listReviews[6]/5);
     Armas weapon7 = new Armas(pre.listPrecio[7], "Armas", "Manamune", 0, pre.listReviews[7], 0, 0, pre.listReviews[7]/3, pre.listReviews[7]/5);
     Armas weapon8 = new Armas(pre.listPrecio[8], "Armas", "Huracán", 0, pre.listReviews[8], 0, 0, pre.listReviews[8]/3, pre.listReviews[8]/5);

    // ARMADURA

     Armadura armor0 = new Armadura(pre.listPrecio[9], "Armadura", "Cotas", 0, 0, pre.listReviews[9], 0, pre.listReviews[9]/4, pre.listReviews[9]/10, "Chaleco con espinas");
     Armadura armor1 = new Armadura(pre.listPrecio[10], "Armadura", "Warmog", 0, 0, pre.listReviews[10], 0, pre.listReviews[10]/4, pre.listReviews[10]/10, "Chaleco grueso");
     Armadura armor2 = new Armadura(pre.listPrecio[11], "Armadura", "Caperuza", 0, 0, pre.listReviews[11], 0, pre.listReviews[11]/4, pre.listReviews[11]/10, "Casco de cuero");
     Armadura armor3 = new Armadura(pre.listPrecio[12], "Armadura", "Segahuesos", 0, 0, pre.listReviews[12], 0, pre.listReviews[12]/4, pre.listReviews[12]/10, "Casco de huesos");
     Armadura armor4 = new Armadura(pre.listPrecio[13], "Armadura", "Botas", 0, 0, pre.listReviews[13], 0, pre.listReviews[13]/4, pre.listReviews[13]/10, "Botas normales");
     Armadura armor5 = new Armadura(pre.listPrecio[14], "Armadura", "Escarpe", 0, 0, pre.listReviews[14], 0, pre.listReviews[14]/4, pre.listReviews[14]/10, "Botas de acero");
     Armadura armor6 = new Armadura(pre.listPrecio[15], "Armadura", "Leeroy ", 0, 0, pre.listReviews[15], 0, pre.listReviews[15]/4, pre.listReviews[15]/10, "Pantalon");
     Armadura armor7 = new Armadura(pre.listPrecio[16], "Armadura", "Jenkins", 0, 0, pre.listReviews[16], 0, pre.listReviews[16]/4, pre.listReviews[16]/10, "Pantalon");

    // CONSUMIBLE

     Consumibles potion0 = new Consumibles(pre.listPrecio[17], "Consumibles", "Pocion pequeña", pre.listReviews[17]/3, 0, 0, 0, 0, 0);
     Consumibles potion1 = new Consumibles(pre.listPrecio[18], "Consumibles", "Pocion mediana", pre.listReviews[18]*2, 0, 0, 0, 0, 0);
     Consumibles potion2 = new Consumibles(pre.listPrecio[19], "Consumibles", "Pocion grande", pre.listReviews[19]*4, 0, 0, 0, 0, 0);

     
    // PERSONAJE
    static Personaje character = new Personaje();

    /**
     * Creates new form Interface
     *
     */
    public Interface() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    // Pone botones en blanco o informacion segun sea el caso
    public void ocultarMostarBotones(Items objeto, JButton boton){
        if (objeto.cantidad_posee == 0){
            // No lo tiene
            boton.setText("");
        } else {
            // Si lo tiene
            
            // Revisa si esta equipado
            if(objeto.equipado){
                // Lo tiene equipado
                boton.setText(objeto.nombre + " <" + objeto.categoria + ">     " + "Equipado");
            } else {
                boton.setText(objeto.nombre + " <" + objeto.categoria + ">     " + "NO Equipado");
            }
        }
        
    }
    
    
    
    // Actualiza los datos que se le presentan al usuario
    public void refresh() {
        // Actualizar JLabels
        //Stats
        JLabelAtaque.setText("Ataque " + character.ataque);
        JLabelDefensa.setText("Defensa " + character.defensa);
        JLabelVelocidad.setText("Velocidad " + character.velocidad);
        JLabelVida.setText("Vida " + character.vida);
        JLabelEstilo.setText("Estilo " + character.estilo);
        JLabelMagia.setText("Magia " + character.magia);
        //Dinero
        JLabelDinero.setText("" + character.dinero);
        
        
        // Actualizar botones de Inventario
        this.ocultarMostarBotones(todos_objetos.get(0), JButtonInventario1);
        this.ocultarMostarBotones(todos_objetos.get(1), JButtonInventario2);
        this.ocultarMostarBotones(todos_objetos.get(2), JButtonInventario3);
    }

    public void preview(Items objeto, Personaje character) {
        JOptionPane.showMessageDialog(null, "PREVIEW"
                + "\nAtaque " + character.ataque + " + " + objeto.ataque
                + "\nDefensa " + character.defensa + " + " + objeto.defensa
                + "\nVida " + character.vida + " + " + objeto.vida
                + "\nVelocidad " + character.velocidad + " + " + objeto.velocidad
                + "\nEstilo " + character.estilo + " + " + objeto.estilo
                + "\nMagia " + character.magia + " + " + objeto.magia);
    }

    public void cargarLista() {
    todos_objetos.add(weapon0);
    todos_objetos.add(weapon1);
    todos_objetos.add(weapon2);
    todos_objetos.add(weapon3);
    todos_objetos.add(weapon4);
    todos_objetos.add(weapon5);
    todos_objetos.add(weapon6);
    todos_objetos.add(weapon7);
    todos_objetos.add(weapon8);

    todos_objetos.add(armor0);
    todos_objetos.add(armor1);
    todos_objetos.add(armor2);
    todos_objetos.add(armor3);
    todos_objetos.add(armor4);
    todos_objetos.add(armor5);
    todos_objetos.add(armor6);
    todos_objetos.add(armor7);       

    todos_objetos.add(potion0);
    todos_objetos.add(potion1);
    todos_objetos.add(potion2);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/fondo_tienda.png"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        JButtonSalir = new javax.swing.JButton();
        JButtonDesequipar = new javax.swing.JButton();
        JButtonEquipar = new javax.swing.JButton();
        JButtonVender = new javax.swing.JButton();
        JButtonComprar = new javax.swing.JButton();
        JPanelTituloTienda = new javax.swing.JPanel();
        JLabelTituloTienda = new javax.swing.JLabel();
        JPanelTituloInventario = new javax.swing.JPanel();
        JLabelTituloInventario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JPanelTienda = new javax.swing.JPanel();
        JButtonTienda1 = new javax.swing.JButton();
        JButtonTienda2 = new javax.swing.JButton();
        JButtomTienda3 = new javax.swing.JButton();
        JButtonTienda4 = new javax.swing.JButton();
        JButtonTienda5 = new javax.swing.JButton();
        JButtonTienda6 = new javax.swing.JButton();
        JButtonTienda7 = new javax.swing.JButton();
        JButtonTienda8 = new javax.swing.JButton();
        JButtonTienda9 = new javax.swing.JButton();
        JButtonTienda10 = new javax.swing.JButton();
        JButtonTienda11 = new javax.swing.JButton();
        JButtonTienda12 = new javax.swing.JButton();
        JButtonTienda13 = new javax.swing.JButton();
        JButtonTienda14 = new javax.swing.JButton();
        JButtonTienda15 = new javax.swing.JButton();
        JButtonTienda16 = new javax.swing.JButton();
        JButtonTienda17 = new javax.swing.JButton();
        JButtonTienda18 = new javax.swing.JButton();
        JButtonTienda19 = new javax.swing.JButton();
        JButtonTienda20 = new javax.swing.JButton();
        JPanelStats = new javax.swing.JPanel();
        JLabelTituloStats = new javax.swing.JLabel();
        JLabelAtaque = new javax.swing.JLabel();
        JLabelDefensa = new javax.swing.JLabel();
        JLabelVida = new javax.swing.JLabel();
        JLabelVelocidad = new javax.swing.JLabel();
        JLabelEstilo = new javax.swing.JLabel();
        JLabelMagia = new javax.swing.JLabel();
        JLabelCoins = new javax.swing.JLabel();
        JLabelDinero = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JPanelInventario = new javax.swing.JPanel();
        JButtonInventario1 = new javax.swing.JButton();
        JButtonInventario2 = new javax.swing.JButton();
        JButtonInventario3 = new javax.swing.JButton();
        JButtonInventario4 = new javax.swing.JButton();
        JButtonInventario5 = new javax.swing.JButton();
        JButtonInventario6 = new javax.swing.JButton();
        JButtonInventario7 = new javax.swing.JButton();
        JButtonInventario8 = new javax.swing.JButton();
        JButtonInventario9 = new javax.swing.JButton();
        JButtonInventario10 = new javax.swing.JButton();
        JButtonInventario11 = new javax.swing.JButton();
        JButtonInventario12 = new javax.swing.JButton();
        JButtonInventario13 = new javax.swing.JButton();
        JButtonInventario14 = new javax.swing.JButton();
        JButtonInventario15 = new javax.swing.JButton();
        JButtonInventario16 = new javax.swing.JButton();
        JButtonInventario17 = new javax.swing.JButton();
        JButtonInventario18 = new javax.swing.JButton();
        JButtonInventario19 = new javax.swing.JButton();
        JButtonInventario20 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        JButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_salir.png"))); // NOI18N
        JButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSalirActionPerformed(evt);
            }
        });

        JButtonDesequipar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_desequipar.png"))); // NOI18N
        JButtonDesequipar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonDesequiparActionPerformed(evt);
            }
        });

        JButtonEquipar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_equipar.png"))); // NOI18N
        JButtonEquipar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEquiparActionPerformed(evt);
            }
        });

        JButtonVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_vender.png"))); // NOI18N
        JButtonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonVenderActionPerformed(evt);
            }
        });

        JButtonComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_comprar.png"))); // NOI18N
        JButtonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonComprarActionPerformed(evt);
            }
        });

        JPanelTituloTienda.setBackground(new java.awt.Color(18, 28, 23));

        JLabelTituloTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/titulo_tienda.png"))); // NOI18N

        javax.swing.GroupLayout JPanelTituloTiendaLayout = new javax.swing.GroupLayout(JPanelTituloTienda);
        JPanelTituloTienda.setLayout(JPanelTituloTiendaLayout);
        JPanelTituloTiendaLayout.setHorizontalGroup(
            JPanelTituloTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelTituloTiendaLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(JLabelTituloTienda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelTituloTiendaLayout.setVerticalGroup(
            JPanelTituloTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelTituloTienda, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        JPanelTituloInventario.setBackground(new java.awt.Color(18, 28, 23));

        JLabelTituloInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/titulo_Inventario.png"))); // NOI18N

        javax.swing.GroupLayout JPanelTituloInventarioLayout = new javax.swing.GroupLayout(JPanelTituloInventario);
        JPanelTituloInventario.setLayout(JPanelTituloInventarioLayout);
        JPanelTituloInventarioLayout.setHorizontalGroup(
            JPanelTituloInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelTituloInventarioLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(JLabelTituloInventario)
                .addGap(139, 139, 139))
        );
        JPanelTituloInventarioLayout.setVerticalGroup(
            JPanelTituloInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelTituloInventarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLabelTituloInventario))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        JPanelTienda.setBackground(new java.awt.Color(0, 0, 51));

        JButtonTienda1.setBackground(new java.awt.Color(29, 70, 252));
        JButtonTienda1.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        JButtonTienda1.setForeground(new java.awt.Color(255, 255, 255));
        JButtonTienda1.setText("Slider<Armas>            100");
        JButtonTienda1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JButtonTienda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonTienda1ActionPerformed(evt);
            }
        });

        JButtonTienda2.setBackground(new java.awt.Color(29, 70, 252));
        JButtonTienda2.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        JButtonTienda2.setForeground(new java.awt.Color(255, 255, 255));
        JButtonTienda2.setText("Chaleco Debil <Armadura>        100");
        JButtonTienda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonTienda2ActionPerformed(evt);
            }
        });

        JButtomTienda3.setBackground(new java.awt.Color(29, 70, 252));
        JButtomTienda3.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        JButtomTienda3.setForeground(new java.awt.Color(255, 255, 255));
        JButtomTienda3.setText("Pocion Pequeña<Consumibles>         25");
        JButtomTienda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtomTienda3ActionPerformed(evt);
            }
        });

        JButtonTienda4.setText("jButton1");

        JButtonTienda5.setText("jButton1");

        JButtonTienda6.setText("jButton4");

        JButtonTienda7.setText("jButton4");

        JButtonTienda8.setText("jButton4");

        JButtonTienda9.setText("jButton4");

        JButtonTienda10.setText("jButton4");

        JButtonTienda11.setText("jButton4");

        JButtonTienda12.setText("jButton4");

        JButtonTienda13.setText("jButton4");

        JButtonTienda14.setText("jButton4");

        JButtonTienda15.setText("jButton4");

        JButtonTienda16.setText("jButton4");

        JButtonTienda17.setText("jButton4");

        JButtonTienda18.setText("jButton4");

        JButtonTienda19.setText("jButton4");

        JButtonTienda20.setText("jButton4");

        javax.swing.GroupLayout JPanelTiendaLayout = new javax.swing.GroupLayout(JPanelTienda);
        JPanelTienda.setLayout(JPanelTiendaLayout);
        JPanelTiendaLayout.setHorizontalGroup(
            JPanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelTiendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JButtonTienda20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtomTienda3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonTienda12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JPanelTiendaLayout.setVerticalGroup(
            JPanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelTiendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JButtonTienda1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtomTienda3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda18, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda19, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonTienda20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(JPanelTienda);

        JPanelStats.setBackground(new java.awt.Color(0, 0, 51));
        JPanelStats.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(51, 51, 51)));

        JLabelTituloStats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/titulo_stats.png"))); // NOI18N

        JLabelAtaque.setBackground(new java.awt.Color(51, 135, 255));
        JLabelAtaque.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        JLabelAtaque.setForeground(new java.awt.Color(255, 255, 255));
        JLabelAtaque.setText("Ataque 10.0");
        JLabelAtaque.setOpaque(true);

        JLabelDefensa.setBackground(new java.awt.Color(51, 135, 255));
        JLabelDefensa.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        JLabelDefensa.setForeground(new java.awt.Color(255, 255, 255));
        JLabelDefensa.setText("Defensa 10.0");
        JLabelDefensa.setOpaque(true);

        JLabelVida.setBackground(new java.awt.Color(51, 135, 255));
        JLabelVida.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        JLabelVida.setForeground(new java.awt.Color(255, 255, 255));
        JLabelVida.setText("Vida 100.0");
        JLabelVida.setOpaque(true);

        JLabelVelocidad.setBackground(new java.awt.Color(51, 135, 255));
        JLabelVelocidad.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        JLabelVelocidad.setForeground(new java.awt.Color(255, 255, 255));
        JLabelVelocidad.setText(" Velocidad 15.0");
        JLabelVelocidad.setOpaque(true);

        JLabelEstilo.setBackground(new java.awt.Color(51, 135, 255));
        JLabelEstilo.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        JLabelEstilo.setForeground(new java.awt.Color(255, 255, 255));
        JLabelEstilo.setText("Estilo 5.0");
        JLabelEstilo.setOpaque(true);

        JLabelMagia.setBackground(new java.awt.Color(51, 135, 255));
        JLabelMagia.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        JLabelMagia.setForeground(new java.awt.Color(255, 255, 255));
        JLabelMagia.setText("Magia 3.0");
        JLabelMagia.setOpaque(true);

        javax.swing.GroupLayout JPanelStatsLayout = new javax.swing.GroupLayout(JPanelStats);
        JPanelStats.setLayout(JPanelStatsLayout);
        JPanelStatsLayout.setHorizontalGroup(
            JPanelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelStatsLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(JLabelTituloStats)
                .addGap(66, 66, 66))
            .addGroup(JPanelStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelAtaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabelDefensa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabelVida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabelVelocidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabelEstilo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabelMagia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JPanelStatsLayout.setVerticalGroup(
            JPanelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelStatsLayout.createSequentialGroup()
                .addComponent(JLabelTituloStats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabelAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLabelDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLabelVida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLabelVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLabelEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLabelMagia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        JLabelCoins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/monedas_oro.png"))); // NOI18N

        JLabelDinero.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        JLabelDinero.setForeground(new java.awt.Color(255, 255, 255));
        JLabelDinero.setText("3500.0");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        JPanelInventario.setBackground(new java.awt.Color(0, 0, 51));

        JButtonInventario1.setBackground(new java.awt.Color(29, 70, 252));
        JButtonInventario1.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        JButtonInventario1.setForeground(new java.awt.Color(255, 255, 255));
        JButtonInventario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonInventario1ActionPerformed(evt);
            }
        });

        JButtonInventario2.setBackground(new java.awt.Color(29, 70, 252));
        JButtonInventario2.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        JButtonInventario2.setForeground(new java.awt.Color(255, 255, 255));
        JButtonInventario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonInventario2ActionPerformed(evt);
            }
        });

        JButtonInventario3.setBackground(new java.awt.Color(29, 70, 252));
        JButtonInventario3.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        JButtonInventario3.setForeground(new java.awt.Color(255, 255, 255));
        JButtonInventario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonInventario3ActionPerformed(evt);
            }
        });

        JButtonInventario4.setText("jButton4");

        JButtonInventario5.setText("jButton1");

        JButtonInventario6.setText("jButton1");

        JButtonInventario7.setText("jButton1");

        JButtonInventario8.setText("jButton1");

        JButtonInventario9.setText("jButton1");

        JButtonInventario10.setText("jButton1");

        JButtonInventario11.setText("jButton1");

        JButtonInventario12.setText("jButton1");

        JButtonInventario13.setText("jButton1");

        JButtonInventario14.setText("jButton1");

        JButtonInventario15.setText("jButton1");

        JButtonInventario16.setText("jButton1");

        JButtonInventario17.setText("jButton1");

        JButtonInventario18.setText("jButton1");

        JButtonInventario19.setText("jButton1");

        JButtonInventario20.setText("jButton1");

        javax.swing.GroupLayout JPanelInventarioLayout = new javax.swing.GroupLayout(JPanelInventario);
        JPanelInventario.setLayout(JPanelInventarioLayout);
        JPanelInventarioLayout.setHorizontalGroup(
            JPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JButtonInventario20, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(JButtonInventario18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(JButtonInventario2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonInventario19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        JPanelInventarioLayout.setVerticalGroup(
            JPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JButtonInventario1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario18, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario19, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonInventario20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(JPanelInventario);

        jDesktopPane1.setLayer(JButtonSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JButtonDesequipar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JButtonEquipar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JButtonVender, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JButtonComprar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JPanelTituloTienda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JPanelTituloInventario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JPanelStats, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JLabelCoins, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JLabelDinero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(JButtonComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButtonVender, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButtonEquipar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JButtonDesequipar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(317, 317, 317)
                        .addComponent(JButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JPanelTituloTienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(JPanelTituloInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPanelStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(JLabelDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLabelCoins)
                                .addGap(24, 24, 24)))))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JButtonDesequipar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JButtonEquipar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(JButtonVender, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(JButtonComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JPanelTituloTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JPanelTituloInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JLabelDinero))
                    .addComponent(JLabelCoins))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPanelStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonComprarActionPerformed
        character.comprar(objeto, procedencia);
        this.refresh();
    }//GEN-LAST:event_JButtonComprarActionPerformed

    private void JButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JButtonSalirActionPerformed

    private void JButtonInventario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonInventario3ActionPerformed
        this.cargarLista();
        objeto = todos_objetos.get(2);

        if (objeto.cantidad_posee == 0){
            // No hay nada entonces no se pasa nada
            objeto = null;
            
        }else {
            // Se indica de donde viene
            procedencia = "inventario";
        }
    }//GEN-LAST:event_JButtonInventario3ActionPerformed

    private void JButtonTienda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonTienda1ActionPerformed
        this.cargarLista();
        objeto = todos_objetos.get(0);
        procedencia = "tienda";
        this.preview(objeto, character);
    }//GEN-LAST:event_JButtonTienda1ActionPerformed

    private void JButtonTienda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonTienda2ActionPerformed
        this.cargarLista();
        objeto = todos_objetos.get(1);
        procedencia = "tienda";
        this.preview(objeto, character);
    }//GEN-LAST:event_JButtonTienda2ActionPerformed

    private void JButtomTienda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtomTienda3ActionPerformed
        this.cargarLista();
        objeto = todos_objetos.get(2);
        procedencia = "tienda";
        this.preview(objeto, character);
    }//GEN-LAST:event_JButtomTienda3ActionPerformed

    private void JButtonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonVenderActionPerformed
        character.vender(objeto, procedencia);
        this.refresh();
    }//GEN-LAST:event_JButtonVenderActionPerformed

    private void JButtonEquiparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEquiparActionPerformed
        character.equipar(objeto, procedencia);
        this.refresh();
    }//GEN-LAST:event_JButtonEquiparActionPerformed

    private void JButtonDesequiparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonDesequiparActionPerformed
        character.desequipar(objeto, procedencia);
        this.refresh();
    }//GEN-LAST:event_JButtonDesequiparActionPerformed

    private void JButtonInventario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonInventario1ActionPerformed
        this.cargarLista();
        objeto = todos_objetos.get(0);

        if (objeto.cantidad_posee == 0){
            // No hay nada entonces no se pasa nada
            objeto = null;
            
        }else {
            // Se indica de donde viene
            procedencia = "inventario";
        }
    }//GEN-LAST:event_JButtonInventario1ActionPerformed

    private void JButtonInventario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonInventario2ActionPerformed
        this.cargarLista();
        objeto = todos_objetos.get(1);

        if (objeto.cantidad_posee == 0){
            // No hay nada entonces no se pasa nada
            objeto = null;
            
        }else {
            // Se indica de donde viene
            procedencia = "inventario";
        }
    }//GEN-LAST:event_JButtonInventario2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtomTienda3;
    private javax.swing.JButton JButtonComprar;
    private javax.swing.JButton JButtonDesequipar;
    private javax.swing.JButton JButtonEquipar;
    private javax.swing.JButton JButtonInventario1;
    private javax.swing.JButton JButtonInventario10;
    private javax.swing.JButton JButtonInventario11;
    private javax.swing.JButton JButtonInventario12;
    private javax.swing.JButton JButtonInventario13;
    private javax.swing.JButton JButtonInventario14;
    private javax.swing.JButton JButtonInventario15;
    private javax.swing.JButton JButtonInventario16;
    private javax.swing.JButton JButtonInventario17;
    private javax.swing.JButton JButtonInventario18;
    private javax.swing.JButton JButtonInventario19;
    private javax.swing.JButton JButtonInventario2;
    private javax.swing.JButton JButtonInventario20;
    private javax.swing.JButton JButtonInventario3;
    private javax.swing.JButton JButtonInventario4;
    private javax.swing.JButton JButtonInventario5;
    private javax.swing.JButton JButtonInventario6;
    private javax.swing.JButton JButtonInventario7;
    private javax.swing.JButton JButtonInventario8;
    private javax.swing.JButton JButtonInventario9;
    private javax.swing.JButton JButtonSalir;
    private javax.swing.JButton JButtonTienda1;
    private javax.swing.JButton JButtonTienda10;
    private javax.swing.JButton JButtonTienda11;
    private javax.swing.JButton JButtonTienda12;
    private javax.swing.JButton JButtonTienda13;
    private javax.swing.JButton JButtonTienda14;
    private javax.swing.JButton JButtonTienda15;
    private javax.swing.JButton JButtonTienda16;
    private javax.swing.JButton JButtonTienda17;
    private javax.swing.JButton JButtonTienda18;
    private javax.swing.JButton JButtonTienda19;
    private javax.swing.JButton JButtonTienda2;
    private javax.swing.JButton JButtonTienda20;
    private javax.swing.JButton JButtonTienda4;
    private javax.swing.JButton JButtonTienda5;
    private javax.swing.JButton JButtonTienda6;
    private javax.swing.JButton JButtonTienda7;
    private javax.swing.JButton JButtonTienda8;
    private javax.swing.JButton JButtonTienda9;
    private javax.swing.JButton JButtonVender;
    private javax.swing.JLabel JLabelAtaque;
    private javax.swing.JLabel JLabelCoins;
    private javax.swing.JLabel JLabelDefensa;
    private javax.swing.JLabel JLabelDinero;
    private javax.swing.JLabel JLabelEstilo;
    private javax.swing.JLabel JLabelMagia;
    private javax.swing.JLabel JLabelTituloInventario;
    private javax.swing.JLabel JLabelTituloStats;
    private javax.swing.JLabel JLabelTituloTienda;
    private javax.swing.JLabel JLabelVelocidad;
    private javax.swing.JLabel JLabelVida;
    private javax.swing.JPanel JPanelInventario;
    private javax.swing.JPanel JPanelStats;
    private javax.swing.JPanel JPanelTienda;
    private javax.swing.JPanel JPanelTituloInventario;
    private javax.swing.JPanel JPanelTituloTienda;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
